### PR TITLE
Enhance/organisation name autofill

### PR DESCRIPTION
**Pull request by Mike-Heneghan**
Hey @digitalWestie,

I added some JS to pre-populated organisation name in the form when redirected from the organisation search page as per https://github.com/Mike-Heneghan/ALISS/issues/29. 

I noticed that one of the tests occasionally fails in test_search.py although it's not something I've been working on so I guess it might be my local environment or an intermittent problem on staging?

Cheers,

Mike

### CODE REVIEW

**Comment by digitalWestie** [comment]
Yeah thought this might come up. I'm using some features that work a bit differently in the various environments. The result is that search scores are calculated differently! For the moment just ignore it if test_search throws up issues.

**Comment by Mike-Heneghan** [comment]
> Yeah thought this might come up. I'm using some features that work a bit differently in the various environments. The result is that search scores are calculated differently! For the moment just ignore it if test_search throws up issues.

Thanks for confirming that. I noticed the Travis fails on this pr have failed but it was just the test_search.py tests as you say.

**Comment by digitalWestie** [comment]
The annoying thing is that it gives inconsistent results. Taking a look at it just now. Also to avoid issues in future you'll need to update your local Elasticsearch to v6.5.4.

**Comment by Mike-Heneghan** [comment]
> The annoying thing is that it gives inconsistent results. Taking a look at it just now. Also to avoid issues in future you'll need to update your local Elasticsearch to v6.5.4.

My current versions are:
```
elasticsearch       5.2.0
elasticsearch-dsl   6.1.0
```
Just to check which versions are you on for them?

**Comment by digitalWestie** [comment]
Oh, to clarify: not the elasticsearch pip packages, but the elasticsearch server itself.

**Comment by digitalWestie** [comment]
If you go to localhost:9200 it should tell you.

**Comment by Mike-Heneghan** [comment]
> If you go to localhost:9200 it should tell you.

It looks like I'm on 6.2.4?
```
{
"name": "HCJVpq3",
"cluster_name": "elasticsearch_mike",
"cluster_uuid": "-3iCpnNkTbeld02aIKLVpw",
"version": {
"number": "6.2.4",
"build_hash": "ccec39f",
"build_date": "2018-04-12T20:37:28.497551Z",
"build_snapshot": false,
"lucene_version": "7.2.1",
"minimum_wire_compatibility_version": "5.6.0",
"minimum_index_compatibility_version": "5.0.0"
},
"tagline": "You Know, for Search"
}
```

**Comment by digitalWestie** [comment]
Yep- that's right, I didn't find good info on updating, so I just removed Elasticsearch and re-installed the specific version.

**Pull request merged**
